// Mocks generated by Mockito 5.4.6 from annotations
// in eazywallet/test/pin_store_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:eazywallet/features/transactions/domain/report_transaction_model.dart'
    as _i4;
import 'package:eazywallet/features/transactions/domain/transaction_model.dart'
    as _i3;
import 'package:eazywallet/features/transactions/domain/user_model.dart' as _i2;
import 'package:eazywallet/features/transactions/domain/wallet_repo.dart'
    as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeUserModel_0 extends _i1.SmartFake implements _i2.UserModel {
  _FakeUserModel_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTransactionModel_1 extends _i1.SmartFake
    implements _i3.TransactionModel {
  _FakeTransactionModel_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeReportTransactionModel_2 extends _i1.SmartFake
    implements _i4.ReportTransactionModel {
  _FakeReportTransactionModel_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [WalletRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockWalletRepository extends _i1.Mock implements _i5.WalletRepository {
  @override
  bool get isPinLocked =>
      (super.noSuchMethod(
            Invocation.getter(#isPinLocked),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i6.Future<_i2.UserModel> fetchDashboard() =>
      (super.noSuchMethod(
            Invocation.method(#fetchDashboard, []),
            returnValue: _i6.Future<_i2.UserModel>.value(
              _FakeUserModel_0(this, Invocation.method(#fetchDashboard, [])),
            ),
            returnValueForMissingStub: _i6.Future<_i2.UserModel>.value(
              _FakeUserModel_0(this, Invocation.method(#fetchDashboard, [])),
            ),
          )
          as _i6.Future<_i2.UserModel>);

  @override
  _i6.Future<List<_i3.TransactionModel>> fetchTransactions() =>
      (super.noSuchMethod(
            Invocation.method(#fetchTransactions, []),
            returnValue: _i6.Future<List<_i3.TransactionModel>>.value(
              <_i3.TransactionModel>[],
            ),
            returnValueForMissingStub:
                _i6.Future<List<_i3.TransactionModel>>.value(
                  <_i3.TransactionModel>[],
                ),
          )
          as _i6.Future<List<_i3.TransactionModel>>);

  @override
  _i6.Future<_i3.TransactionModel> fetchTransactionById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#fetchTransactionById, [id]),
            returnValue: _i6.Future<_i3.TransactionModel>.value(
              _FakeTransactionModel_1(
                this,
                Invocation.method(#fetchTransactionById, [id]),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i3.TransactionModel>.value(
              _FakeTransactionModel_1(
                this,
                Invocation.method(#fetchTransactionById, [id]),
              ),
            ),
          )
          as _i6.Future<_i3.TransactionModel>);

  @override
  _i6.Future<_i4.ReportTransactionModel> submitTransactionReport({
    required String? transactionId,
    required _i4.ReportReason? reason,
    required String? description,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#submitTransactionReport, [], {
              #transactionId: transactionId,
              #reason: reason,
              #description: description,
            }),
            returnValue: _i6.Future<_i4.ReportTransactionModel>.value(
              _FakeReportTransactionModel_2(
                this,
                Invocation.method(#submitTransactionReport, [], {
                  #transactionId: transactionId,
                  #reason: reason,
                  #description: description,
                }),
              ),
            ),
            returnValueForMissingStub:
                _i6.Future<_i4.ReportTransactionModel>.value(
                  _FakeReportTransactionModel_2(
                    this,
                    Invocation.method(#submitTransactionReport, [], {
                      #transactionId: transactionId,
                      #reason: reason,
                      #description: description,
                    }),
                  ),
                ),
          )
          as _i6.Future<_i4.ReportTransactionModel>);

  @override
  _i6.Future<bool> verifyTransactionPin(String? pin) =>
      (super.noSuchMethod(
            Invocation.method(#verifyTransactionPin, [pin]),
            returnValue: _i6.Future<bool>.value(false),
            returnValueForMissingStub: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);
}
